name: "Chromatic Deployment"

on:
  pull_request:
    branches:
      - develop

# permissions:
#   contents: write
#   pages: write
#   deployments: write
#   id-token: write
#   issues: write
#   pull-requests: write

jobs:
  chromatic-deployment:
    name: Chromatic
    runs-on: ubuntu-latest
    outputs:
      statis: ${{ job.status }}
      storybook_url: ${{ steps.chromatic.outputs.storybookUrl }}
      currnent_time: ${{ steps.current-time.outputs.formattedTime }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          exitZeroOnChanges: true
          autoAcceptChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.TOKEN }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: "YYYYÎÖÑ MMÏõî DDÏùº HHÏãú mmÎ∂Ñ"
          utcOffset: "+09:00"

  github-bot-storybook:
    runs-on: ubuntu-latest
    needs: [chromatic-deployment]
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          comment-tag: ${{ github.event.number }}-storybook
          message: |

            üíÑ Storybook: ${{ needs.chromatic-deployment.outputs.storybook_url }}
            üïñ Update: ${{ needs.chromatic-deployment.outputs.currnent_time }}
